
CREATE TABLE projects (
	p_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	p_name VARBINARY(255) NOT NULL,
	p_description BLOB,
	PRIMARY KEY (p_id),
	UNIQUE (p_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE remotes (
	r_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	r_project INTEGER NOT NULL,
	r_name VARBINARY(40) NOT NULL,
	r_user INTEGER UNSIGNED NOT NULL,
	r_url VARBINARY(255) NOT NULL,
	PRIMARY KEY (r_id),
	UNIQUE r_unique (r_project,r_name),
	UNIQUE (r_user)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
